### ISSUE TITLE
Older port

### ISSUE THREAD

**Issue by OnesAndZer0s** [Elveskevtar/SmarterMoving#1]
Hey, so I found an older [port](https://github.com/Tommsy64/SmartMovingReloaded) of Smart Movement, but it is broken and incompatible with a lot of mods. The only thing I’ve noticed is that the hit box doesn’t change once crawling. I’ve tried opening it up and fixing some values, but I haven’t figured out how to work eclipse yet, and the mod is giving me a hard time. I’m wondering if it would be of any use to use some of this code for your port of Smart Movement.

Besides that, keep it up dude! You’re doing great!

**Comment by elveskevtar** [comment]
Hey @OnesAndZer0s thank you for this. This port is actually what initially inspired me to work on the mod in the first place. I got crawling working actually (there is a bug that lets people crawl at normal speed but I'm working on it). I appreciate this though :) thank you.

Let me know if you would like to test the mod and I will send you the jar!

**Comment by OnesAndZer0s** [comment]
I’ve actually tested the mod out already and it’s extremely promising! I compiled it yesterday and tested it out, and that’s what got me to write the issue. I tried rewriting some of the classes in the old port that didn’t change the hitbox correctly, but it decided it wasn’t going to cooperate, I guess. So, I was curious on how difficult it would be to try and use some of the code as examples. It seems like both ports are using the same apis, so it shouldn’t require rewriting lines upon lines of code.

Besides that, there is also a mod, [Up and Down and All Around](https://github.com/Mysteryem/Up_And_Down_And_All_Around), that had conflicting classes with the other port. It looks like the mod is gaining some traction, as well. Do you know if it would be possible to add support for this mod? I haven’t learned enough Java to understand if it’s possible to integrate the mods.

Besides all of that ramble, keep it up, you’re doing great!

**Comment by elveskevtar** [comment]
Hey omg, I didn't even see this sorry! I will definitely add it to the project board but it may not get worked on until the mod is mostly ported over (most movement types are done).

Also, I'm not sure if you are on the discord: https://discord.gg/B7gh8YC
